In [ ]:
import numpy as np
import pandas as pd

## StandardScaler

In [8]:
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()

print(scaler.fit(data))
print(scaler.mean_)
print(scaler.var_)
print(scaler.scale_)

print("\n")
print(scaler.transform(data))
print(scaler.transform([[0.5, 0.5]]))
print(scaler.transform([[2, 2]]))

StandardScaler(copy=True, with_mean=True, with_std=True)
[ 0.5  0.5]
[ 0.25  0.25]
[ 0.5  0.5]


[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 0.  0.]]
[[ 3.  3.]]


<h1>Forward Stepwise Selection</h1>

In [ ]:
df = pd.read_csv("kc_house_data.csv")
df.drop(['id','date','zipcode',],axis=1,inplace=True)